apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-mundos-e
  namespace: mundos-e-nginx
  labels:
    app: mundose-eks-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mundose-eks-nginx
  template:
    metadata:
      labels:
        app: mundose-eks-nginx
    spec:
      containers:
      - name: eks-mundos-e
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443