apiVersion: v1
kind: Service
metadata:
  name: mundose-eks-nginx
  namespace: mundos-e-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: mundose-eks-nginx